---
train:

    params:
        # batch_size: 512
        batch_size: 32
        epoch: 50
        lr: 0.0005
        decay: 0.5
        decay_step: 10
        warmup: 3

    save:
        # metapath: "/userhome/share_hosts/work/Transformer/ComTrans/exp/Transformer-6layers"
        # folder: eth
        # model_name: trans6
        # metapath: "C:\\Users\\victus\\Documents\\git-project\\capstone\\GazeTR\\GazeTR"
        # folder: model
        # model_name: GazeTR-H-ETH
        metapath: "C:\\Users\\victus\\Documents\\git-project\\capstone\\gaze-swin\\model"
        # TODO CHANGE THIS NEXT LINE
        folder: xgaze-small-1
        model_name: GazeSwin
        step: 5

    data:
        # image: "/userdata/ETH.zip/ETH-Gaze/Image/train"
        # label: "/userdata/ETH.zip/ETH-Gaze/Label/trainYP.label"
        # TODO CHANGE THESE 2 LINES
        # image: "C:/Users/victus/Documents/git-project/capstone/dataset-sample/xgaze-full/Image"
        # label: "C:/Users/victus/Documents/git-project/capstone/dataset-sample/xgaze-dvgaze-full/Label/train.label"
        image: "C:/Users/victus/Documents/git-project/capstone/dataset-sample/xgaze-small-1/Image"
        label: "C:/Users/victus/Documents/git-project/capstone/dataset-sample/xgaze-small-1/Label/train.label"
        header: True
        name: eth
        isFolder: False

    pretrain:
        enable: False
        path: PLACEHOLDER
        device: PLACEHOLDER

    device: 0

    reader: reader

# dropout = 0
# dim_feed = 512
